Repository mitodl/hugo-course-publisher, pull requests merged in 2020-11, with the labels that each got.

#291 a few tweaks to cut down bundle size
  package.json
  src/css/main.scss
  src/index.js
  src/js/components/Facet.js
  src/js/components/FacetDisplay.js
  src/js/components/FilterableFacet.js
  src/js/components/SearchFilter.test.js
  yarn.lock
Labels: Waiting on author

#289 Tweak course cards to be 300px wide on desktop view
  site/layouts/partials/home_course_cards.html
  src/css/home.scss
Labels: Waiting on author, blocked

#285 add suggestions UI to Search
  src/css/search.scss
  src/js/components/SearchPage.js
  src/js/components/SearchPage.test.js
  src/js/lib/util.js
Labels: blocked

#293 Adjustments for social and signup link cards
  site/static/images/social-facebook-blue.svg
  site/static/images/social-facebook.svg
  site/static/images/social-instagram-blue.svg
  site/static/images/social-instagram.svg
  site/static/images/social-twitter-blue.svg
  site/static/images/social-twitter.svg
  site/static/images/social-youtube-blue.svg
  site/static/images/social-youtube.svg
  site/themes/multi_course/layouts/home.html
  src/css/home.scss
Labels: Needs review

#297 Import bootstrap JS to fix carousel buttons
  src/index.js
Labels: Needs review

#300 Enable static/hash.txt for CI deployment
  package.json
Labels: Needs review

#305 Link to the most recent published course run url
  src/js/factories/search.js
  src/js/lib/search.js
  src/js/lib/search.test.js
Labels: Needs review

#320 Update ocw-to-hugo
  package.json
  yarn.lock
Labels: Needs review

#304 switch to github actions
  .github/workflows/ci.yml
  .travis.yml
Labels: Waiting on author

#298 Implement Mailchimp signup
  site/layouts/partials/newsletter_signup.html
  site/themes/multi_course/layouts/home.html
  src/index.js
  src/js/mailchimp.js
Labels: Waiting on author

#329 split up course_features.html
  site/layouts/course/baseof.html
  site/layouts/partials/course_features.html
  site/layouts/partials/course_info.html
  site/layouts/partials/topics.html
Labels: Waiting on author

#319 remove links from Course no., "As Taught In" in course info
  site/layouts/partials/course_info.html
  site/layouts/partials/course_instructor_number.html
  site/layouts/partials/partial_collapse_list.html
Labels: Waiting on author

#325 Instructor search links
  site/layouts/partials/course_info.html
  site/layouts/partials/course_instructor_number.html
  src/js/components/SearchResult.js
  src/js/course_info_links.js
  src/js/course_info_links.test.js
Labels: Waiting on author

#332 Re-enable topic search
  site/layouts/partials/topic.html
  src/js/course_info_links.js
  src/js/course_info_links.test.js
Labels: Needs review

#327 Set page titles
  site/config.toml
  site/config_zip.toml
  site/content/_index.md
  site/layouts/_default/baseof.html
  site/layouts/course/baseof.html
  site/layouts/partials/title.html
  src/js/components/SearchBox.js
  src/js/components/SearchBox.test.js
Labels: Waiting on author

#342 Update markdown file to match ocw-to-hugo boilerplate
  site/content/_index.md
Labels: Waiting on author

#340 desktop course info toggle
  site/layouts/course/baseof.html
  src/css/course-nav.scss
  src/index.js
  src/js/course_info_toggle.js
  src/js/lib/constants.js
Labels: Waiting on author

#343 update home page styles
  site/static/images/homepage_hero.png
  site/static/images/ocw_logo_white.png
  site/themes/multi_course/layouts/home.html
  src/css/header.scss
  src/css/home.scss
  src/css/main.scss
  src/css/search.scss
  src/css/variables.scss
  src/index.js
  src/js/components/HomeSearchBox.js
  src/js/components/HomeSearchBox.test.js
  src/js/components/SearchBox.js
  src/js/components/SearchBox.test.js
  src/js/components/SearchPage.js
Labels: Waiting on author

#344 fix search filter title wrapping
  src/css/search-filter.scss
Labels: Waiting on author

#349 upgrade ocw-to-hugo, add support for simplecast
  package.json
  site/layouts/shortcodes/simplecast.html
  yarn.lock
Labels: Waiting on author

#348 Don't activate desktop toggle for other pages
  src/js/course_info_toggle.js
Labels: Waiting on author

#346 Update topics partials to use new data structure
  package.json
  site/layouts/partials/topic.html
  site/layouts/partials/topics.html
  site/layouts/partials/topics_summary.html
  yarn.lock
Labels: Needs review

#352 fix two style oopsies
  site/themes/multi_course/layouts/home.html
  src/css/home.scss
Labels: Waiting on author

#351 course banner
  site/layouts/course/baseof.html
  site/layouts/course/course_home.html
  site/layouts/course/course_section.html
  site/layouts/partials/course_banner.html
  site/layouts/partials/course_content.html
  src/css/bootstrap-overrides.scss
  src/css/header.scss
  src/css/main.scss
Labels: Waiting on author

#363 home page second pass
  site/layouts/course/course_home.html
  site/layouts/course/course_section.html
  site/layouts/partials/header.html
  site/layouts/partials/header_placeholder.html
  site/layouts/partials/home_course_cards.html
  site/layouts/search/section.html
  site/static/images/heart.png
  site/static/images/homepage_bg.png
  site/static/images/homepage_hero.png
  site/themes/multi_course/layouts/home.html
  src/css/header.scss
  src/css/home.scss
  src/css/search.scss
  src/css/variables.scss
Labels: Needs review

#347 Style updates to course home page
  site/layouts/course/baseof.html
  site/layouts/course/course_home.html
  site/layouts/partials/course_feature.html
  site/layouts/partials/course_features.html
  site/layouts/partials/course_info.html
  site/layouts/partials/mobile_course_info.html
  site/layouts/partials/topics_oneline.html
  site/themes/multi_course/layouts/partials/chp_partial.html
  site/themes/single_course/layouts/partials/chp_partial.html
  src/css/course-home.scss
  src/css/course-info.scss
  src/css/main.scss
  src/css/search.scss
Labels: Needs review

#366 remove 'theme engine'
  src/css/gitbook.scss
  src/css/main.scss
  src/index.js
  src/js/stylesheets.js
Labels: Waiting on author

#373 design tweak: header height to 70px
  src/css/header.scss
Labels: Waiting on author

#375 update background image file for home screen
  site/static/images/homepage_bg.png
Labels: Waiting on author

#364 course page content text style
  site/layouts/partials/course_content.html
  src/css/main.scss
Labels: Waiting on author

#376 fix header and course_banner usage
  site/layouts/course/baseof.html
  site/layouts/course/course_home.html
  site/layouts/course/course_section.html
Labels: Needs review

#378 add corporate sponsors section
  site/static/images/sponsor_logos/ab_initio.png
  site/static/images/sponsor_logos/accenture.png
  site/static/images/sponsor_logos/dow.png
  site/static/images/sponsor_logos/lockheed.png
  site/static/images/sponsor_logos/mathworks.png
  site/static/images/sponsor_logos/telmex.png
  site/themes/multi_course/layouts/home.html
  src/css/home.scss
Labels: Needs review

#386 Adjust border radius of carousel card to match image
  src/css/home.scss
Labels: Needs review

#387 Add back check for course_info params
  site/layouts/partials/course_features.html
  site/layouts/partials/course_info.html
Labels: Needs review

#359 Use material-design-icons
  package.json
  site/layouts/_default/baseof.html
  site/layouts/course/baseof.html
  site/layouts/partials/head.html
  site/layouts/partials/webpack_url.html
  src/css/main.scss
  src/fonts/material-design-icons/MaterialIcons-Regular.ttf
  src/fonts/material-design-icons/MaterialIcons-Regular.woff
  src/fonts/material-design-icons/MaterialIcons-Regular.woff2
  yarn.lock
Labels: Needs review

#390 expand example_courses.json
  example_courses.json
Labels: Waiting on author

#394 design tweaks
  site/layouts/partials/course_features.html
  site/layouts/partials/course_info.html
  site/layouts/partials/topic.html
  site/layouts/partials/topics.html
  site/layouts/partials/topics_oneline.html
  src/css/course-home.scss
Labels: Needs review

#397 fix image caption / image alt text issue
  site/layouts/course/course_home.html
  src/css/course-home.scss
Labels: Waiting on author

#400 make the course banner text a link to the course home page
  site/layouts/course/baseof.html
  site/layouts/partials/course_banner.html
  src/css/header.scss
Labels: Waiting on author

#401 remove small arrow on home page
  site/themes/multi_course/layouts/home.html
Labels: Waiting on author

#402 fix link styling
  site/layouts/partials/topic.html
  site/layouts/partials/topics_oneline.html
Labels: Waiting on author

#396 Implement collapse/expand for course info
  site/layouts/partials/course_info.html
  src/css/course-info.scss
  src/index.js
  src/js/course_expander.js
Labels: Needs review

#404 Fix course description title
  site/layouts/course/course_home.html
  src/css/course-home.scss
Labels: Needs review

#403 carousel image should be a link too
  site/layouts/partials/home_course_cards.html
Labels: Waiting on author

#407 fix course feature spacing
  site/layouts/partials/course_feature.html
Labels: Waiting on author

#408 update homepage hero image
  site/static/images/homepage_hero.jpg
  site/static/images/homepage_hero.png
  site/themes/multi_course/layouts/home.html
Labels: Waiting on author

#393 sprinkle partialCached here and there
  site/layouts/course/baseof.html
  site/layouts/partials/desktop_course_info.html
  site/layouts/search/section.html
Labels: Waiting on author

#412 add hover effect, add some padding so it's visible
  site/layouts/partials/home_course_cards.html
  src/css/home.scss
Labels: Waiting on author
